"""Generate markdown tables and charts from benchmark results."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import matplotlib
matplotlib.use("Agg")  # headless rendering — no GUI required
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from tabulate import tabulate

from graph_bench.config import RESULTS_DIR, get_platform_specs

# Consistent color palette across all charts.
# Chosen to be distinguishable on screen and in print.
_PALETTE = [
    "#4C72B0",  # steel blue  – CognoDB
    "#DD8452",  # muted orange – Neo4j
    "#55A868",  # sage green   – Memgraph
    "#C44E52",  # brick red    – FalkorDB
    "#8172B2",  # lavender     – ArangoDB
    "#937860",  # tan          – extra
]

_PLATFORM_ORDER = ["cognodb", "neo4j", "memgraph", "falkordb", "arangodb"]


def _platform_color(name: str, idx: int) -> str:
    """Return a stable color for a platform by name, falling back to index."""
    lower = name.lower()
    if "cogno" in lower:
        return _PALETTE[0]
    if "neo4j" in lower or "aura" in lower:
        return _PALETTE[1]
    if "memgraph" in lower:
        return _PALETTE[2]
    if "falkor" in lower:
        return _PALETTE[3]
    if "arango" in lower:
        return _PALETTE[4]
    return _PALETTE[idx % len(_PALETTE)]


def load_latest_results(results_dir: Path | None = None) -> dict[str, Any]:
    path = (results_dir or RESULTS_DIR) / "latest.json"
    if not path.exists():
        raise FileNotFoundError(
            f"No results at {path}. Run `graph-bench run` first."
        )
    return json.loads(path.read_text(encoding="utf-8"))


def _fmt_latency(stats: dict[str, Any] | None) -> str:
    if not stats:
        return "N/A"
    p50 = stats.get("p50_ms", 0)
    p95 = stats.get("p95_ms", 0)
    errs = stats.get("errors", 0)
    suffix = f" ⚠ {errs} err" if errs else ""
    return f"p50={p50:.1f} / p95={p95:.1f} ms{suffix}"


def _fmt_cold(cold: float | None) -> str:
    if cold is None:
        return "N/A"
    return f"{cold:.1f} ms"


def generate_markdown_report(results: dict[str, Any], output: Path) -> str:
    specs = get_platform_specs()
    lines: list[str] = [
        "# Benchmark Results Report",
        "",
        "Auto-generated by `graph-bench report` from `results/latest.json`.",
        "",
        "## Instance Specifications",
        "",
        tabulate(
            [
                [
                    specs[k].name if k in specs else r.get("platform_name", k),
                    specs[k].tier if k in specs else "—",
                    specs[k].vcpu if k in specs else "—",
                    specs[k].ram_mb if k in specs else "—",
                    specs[k].storage_gb if k in specs else "—",
                ]
                for k, r in results.items()
            ],
            headers=["Platform", "Tier", "vCPU", "RAM (MB)", "Storage (GB)"],
            tablefmt="github",
        ),
        "",
        "## Data Loading",
        "",
        tabulate(
            [
                [
                    r.get("platform_name", k),
                    ld.get("wall_clock_seconds", "N/A"),
                    f"{ld.get('nodes_per_second', 0):,.0f}",
                    f"{ld.get('relationships_per_second', 0):,.0f}",
                    ld.get("method", ""),
                ]
                for k, r in results.items()
                for ld in [r.get("load", {})]
            ],
            headers=[
                "Platform",
                "Load time (s)",
                "Nodes/s",
                "Rels/s",
                "Method",
            ],
            tablefmt="github",
        ),
        "",
        "## Cold-Start vs Warm Traversal Latency",
        "",
        "> Cold-start: single 1-hop query immediately after data load, before any warm-up.",
        "> Warm: p50/p95 over ≥100 iterations after 10 warm-up rounds.",
        "",
        tabulate(
            [
                [
                    r.get("platform_name", k),
                    _fmt_cold(r.get("cold_start_ms")),
                    _fmt_latency(r.get("traversals", {}).get("1_hop")),
                    _fmt_latency(r.get("traversals", {}).get("2_hop")),
                    _fmt_latency(r.get("traversals", {}).get("3_hop")),
                ]
                for k, r in results.items()
            ],
            headers=["Platform", "Cold 1-hop", "1-hop (warm)", "2-hop", "3-hop"],
            tablefmt="github",
        ),
        "",
        "## Lookups",
        "",
        "> Indexes on `Person.id` (point) and `Person.community` (filtered) on every platform.",
        "",
        tabulate(
            [
                [
                    r.get("platform_name", k),
                    _fmt_latency(r.get("lookups", {}).get("point_lookup")),
                    _fmt_latency(r.get("lookups", {}).get("filtered_lookup")),
                ]
                for k, r in results.items()
            ],
            headers=["Platform", "Point lookup (id)", "Filtered lookup (community)"],
            tablefmt="github",
        ),
        "",
        "## Aggregations",
        "",
        "> Top-10 communities by neighbour count — closest to an analytic scan.",
        "",
        tabulate(
            [
                [
                    r.get("platform_name", k),
                    _fmt_latency(r.get("aggregations", {}).get("group_by_community")),
                ]
                for k, r in results.items()
            ],
            headers=["Platform", "Group-by community (top 10)"],
            tablefmt="github",
        ),
        "",
        "## Mixed Workload (80/20 read/write)",
        "",
    ]

    mixed_rows = []
    for k, r in results.items():
        for mk, mv in r.get("mixed_workload", {}).items():
            conc = mk.replace("concurrency_", "")
            mixed_rows.append(
                [
                    r.get("platform_name", k),
                    conc,
                    f"{mv.get('queries_per_second', 0):.1f}",
                    mv.get("total_queries", 0),
                    mv.get("errors", 0),
                ]
            )
    lines.append(
        tabulate(
            mixed_rows,
            headers=["Platform", "Concurrency", "QPS", "Total queries", "Errors"],
            tablefmt="github",
        )
    )

    lines.extend(["", "## Footprint", ""])
    footprint_rows = []
    for k, r in results.items():
        fp = r.get("footprint", {})
        footprint_rows.append(
            [
                r.get("platform_name", k),
                fp.get("stored_data_size", "N/A"),
                fp.get("memory_usage", "N/A"),
                fp.get("notes", ""),
            ]
        )
    lines.append(
        tabulate(
            footprint_rows,
            headers=["Platform", "Stored size", "Memory", "Notes"],
            tablefmt="github",
        )
    )

    caveats = []
    for k, r in results.items():
        for c in r.get("caveats", []):
            caveats.append(f"- **{r.get('platform_name', k)}**: {c}")
    if caveats:
        lines.extend(["", "## Caveats", ""] + caveats)

    lines.extend(["", "## Charts", ""])
    chart_dir = output.parent / "charts"
    for chart_name, title in [
        ("traversal_latency.png", "Traversal Latency by Hop Depth"),
        ("lookup_latency.png", "Lookup Latency (Point vs Filtered)"),
        ("aggregation_latency.png", "Aggregation Latency"),
        ("ingest_throughput.png", "Ingest Throughput (Relationships/s)"),
        ("mixed_workload_qps.png", "Mixed Workload QPS vs Concurrency"),
    ]:
        chart_path = chart_dir / chart_name
        if chart_path.exists():
            lines.append(f"![{title}](charts/{chart_name})")
            lines.append("")

    content = "\n".join(lines) + "\n"
    output.write_text(content, encoding="utf-8")
    return content


def _apply_chart_style(ax: plt.Axes, title: str, ylabel: str) -> None:
    """Apply consistent styling to a chart axes."""
    ax.set_title(title, fontsize=13, fontweight="bold", pad=12)
    ax.set_ylabel(ylabel, fontsize=10)
    ax.yaxis.grid(True, linestyle="--", linewidth=0.6, alpha=0.7)
    ax.set_axisbelow(True)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)


def generate_charts(results: dict[str, Any], output_dir: Path) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    paths: list[Path] = []

    platforms = list(results.keys())
    platform_names = [results[k].get("platform_name", k) for k in platforms]
    colors = [_platform_color(n, i) for i, n in enumerate(platform_names)]

    # ── Chart 1: Traversal latency (grouped bar — p50 and p95 per hop) ──────
    rows = []
    for k, r in results.items():
        for hop in ("1_hop", "2_hop", "3_hop"):
            stats = r.get("traversals", {}).get(hop)
            if stats:
                rows.append(
                    {
                        "platform": r.get("platform_name", k),
                        "hop": hop.replace("_", "-"),
                        "p50_ms": stats["p50_ms"],
                        "p95_ms": stats["p95_ms"],
                    }
                )
    if rows:
        df = pd.DataFrame(rows)
        hops = df["hop"].unique()
        x = np.arange(len(hops))
        width = 0.8 / max(len(platform_names) * 2, 1)

        fig, ax = plt.subplots(figsize=(11, 5))
        for i, (name, color) in enumerate(zip(platform_names, colors)):
            sub = df[df["platform"] == name]
            p50_vals = [sub[sub["hop"] == h]["p50_ms"].values[0] if h in sub["hop"].values else 0 for h in hops]
            p95_vals = [sub[sub["hop"] == h]["p95_ms"].values[0] if h in sub["hop"].values else 0 for h in hops]
            offset = (2 * i - len(platform_names) + 0.5) * width
            ax.bar(x + offset - width / 2, p50_vals, width, label=f"{name} p50",
                   color=color, alpha=0.85)
            ax.bar(x + offset + width / 2, p95_vals, width, label=f"{name} p95",
                   color=color, alpha=0.45, hatch="//")
        ax.set_xticks(x)
        ax.set_xticklabels(hops)
        _apply_chart_style(ax, "Traversal Latency by Hop Depth", "Latency (ms)")
        ax.legend(bbox_to_anchor=(1.02, 1), loc="upper left", fontsize=8, framealpha=0.9)
        fig.tight_layout()
        p = output_dir / "traversal_latency.png"
        fig.savefig(p, dpi=200, bbox_inches="tight")
        plt.close(fig)
        paths.append(p)

    # ── Chart 2: Lookup latency (grouped bar — point vs filtered) ────────────
    lookup_rows = []
    for k, r in results.items():
        for ltype in ("point_lookup", "filtered_lookup"):
            stats = r.get("lookups", {}).get(ltype)
            if stats:
                lookup_rows.append(
                    {
                        "platform": r.get("platform_name", k),
                        "type": "Point (id)" if ltype == "point_lookup" else "Filtered (community)",
                        "p50_ms": stats["p50_ms"],
                        "p95_ms": stats["p95_ms"],
                    }
                )
    if lookup_rows:
        df = pd.DataFrame(lookup_rows)
        ltypes = df["type"].unique()
        x = np.arange(len(ltypes))
        width = 0.8 / max(len(platform_names) * 2, 1)

        fig, ax = plt.subplots(figsize=(9, 5))
        for i, (name, color) in enumerate(zip(platform_names, colors)):
            sub = df[df["platform"] == name]
            p50_vals = [sub[sub["type"] == t]["p50_ms"].values[0] if t in sub["type"].values else 0 for t in ltypes]
            p95_vals = [sub[sub["type"] == t]["p95_ms"].values[0] if t in sub["type"].values else 0 for t in ltypes]
            offset = (2 * i - len(platform_names) + 0.5) * width
            ax.bar(x + offset - width / 2, p50_vals, width, label=f"{name} p50",
                   color=color, alpha=0.85)
            ax.bar(x + offset + width / 2, p95_vals, width, label=f"{name} p95",
                   color=color, alpha=0.45, hatch="//")
        ax.set_xticks(x)
        ax.set_xticklabels(ltypes)
        _apply_chart_style(ax, "Lookup Latency — Point vs Filtered", "Latency (ms)")
        ax.legend(bbox_to_anchor=(1.02, 1), loc="upper left", fontsize=8, framealpha=0.9)
        fig.tight_layout()
        p = output_dir / "lookup_latency.png"
        fig.savefig(p, dpi=200, bbox_inches="tight")
        plt.close(fig)
        paths.append(p)

    # ── Chart 3: Aggregation latency (horizontal bar) ────────────────────────
    agg_rows = [
        {
            "platform": r.get("platform_name", k),
            "p50_ms": (r.get("aggregations", {}).get("group_by_community") or {}).get("p50_ms", 0),
            "p95_ms": (r.get("aggregations", {}).get("group_by_community") or {}).get("p95_ms", 0),
        }
        for k, r in results.items()
        if r.get("aggregations", {}).get("group_by_community")
    ]
    if agg_rows:
        df = pd.DataFrame(agg_rows)
        fig, ax = plt.subplots(figsize=(8, max(3, len(agg_rows) * 0.7 + 1)))
        y = np.arange(len(df))
        h = 0.35
        bar_colors = [_platform_color(n, i) for i, n in enumerate(df["platform"])]
        ax.barh(y + h / 2, df["p50_ms"], h, label="p50", color=bar_colors, alpha=0.85)
        ax.barh(y - h / 2, df["p95_ms"], h, label="p95", color=bar_colors, alpha=0.45, hatch="//")
        ax.set_yticks(y)
        ax.set_yticklabels(df["platform"])
        ax.set_xlabel("Latency (ms)", fontsize=10)
        _apply_chart_style(ax, "Aggregation Latency — Group-by Community", "Latency (ms)")
        ax.xaxis.grid(True, linestyle="--", linewidth=0.6, alpha=0.7)
        ax.yaxis.grid(False)
        ax.legend(fontsize=9, framealpha=0.9)
        fig.tight_layout()
        p = output_dir / "aggregation_latency.png"
        fig.savefig(p, dpi=200, bbox_inches="tight")
        plt.close(fig)
        paths.append(p)

    # ── Chart 4: Ingest throughput (vertical bar — rels/s) ───────────────────
    load_rows = [
        {
            "platform": r.get("platform_name", k),
            "rels_per_sec": r.get("load", {}).get("relationships_per_second", 0),
        }
        for k, r in results.items()
        if r.get("load")
    ]
    if load_rows:
        df = pd.DataFrame(load_rows)
        bar_colors = [_platform_color(n, i) for i, n in enumerate(df["platform"])]
        fig, ax = plt.subplots(figsize=(8, 4))
        bars = ax.bar(df["platform"], df["rels_per_sec"], color=bar_colors, alpha=0.85, edgecolor="white")
        for bar in bars:
            h = bar.get_height()
            if h > 0:
                ax.text(
                    bar.get_x() + bar.get_width() / 2,
                    h * 1.01,
                    f"{h:,.0f}",
                    ha="center",
                    va="bottom",
                    fontsize=8,
                )
        _apply_chart_style(ax, "Ingest Throughput — Relationships / second", "Relationships / second")
        plt.xticks(rotation=20, ha="right", fontsize=9)
        fig.tight_layout()
        p = output_dir / "ingest_throughput.png"
        fig.savefig(p, dpi=200, bbox_inches="tight")
        plt.close(fig)
        paths.append(p)

    # ── Chart 5: Mixed workload QPS vs concurrency (line plot) ───────────────
    mixed_rows = []
    for k, r in results.items():
        for mk, mv in r.get("mixed_workload", {}).items():
            mixed_rows.append(
                {
                    "platform": r.get("platform_name", k),
                    "concurrency": int(mk.replace("concurrency_", "")),
                    "qps": mv.get("queries_per_second", 0),
                    "errors": mv.get("errors", 0),
                }
            )
    if mixed_rows:
        df = pd.DataFrame(mixed_rows).sort_values("concurrency")
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 5))
        for i, (name, color) in enumerate(zip(platform_names, colors)):
            sub = df[df["platform"] == name]
            if sub.empty:
                continue
            ax1.plot(sub["concurrency"], sub["qps"], marker="o", label=name, color=color, linewidth=2)
            ax2.plot(sub["concurrency"], sub["errors"], marker="s", label=name, color=color,
                     linewidth=2, linestyle="--")
        ax1.set_xlabel("Concurrency (clients)", fontsize=10)
        _apply_chart_style(ax1, "Mixed Workload QPS", "Queries / second")
        ax1.legend(fontsize=9, framealpha=0.9)
        ax2.set_xlabel("Concurrency (clients)", fontsize=10)
        _apply_chart_style(ax2, "Mixed Workload Error Count", "Error count")
        ax2.legend(fontsize=9, framealpha=0.9)
        fig.suptitle("80/20 Read/Write Mix — 60 seconds", fontsize=12, y=1.01)
        fig.tight_layout()
        p = output_dir / "mixed_workload_qps.png"
        fig.savefig(p, dpi=200, bbox_inches="tight")
        plt.close(fig)
        paths.append(p)

    return paths


def generate_report(results_dir: Path | None = None) -> Path:
    results_dir = results_dir or RESULTS_DIR
    results = load_latest_results(results_dir)
    report_path = results_dir / "REPORT.md"
    generate_markdown_report(results, report_path)
    generate_charts(results, results_dir / "charts")
    return report_path
